version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_CONSOLE_LOG_LEVEL=Debug
      - Logging__Console__LogLevel__Default=Debug
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - ambev.developerevaluation.database

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13

    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped

  # ambev.developerevaluation.nosql:
  #   container_name: ambev_developer_evaluation_nosql 
  #   image: mongo:8.0    
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: developer
  #       MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #     - "27017"

  # ambev.developerevaluation.cache:
  #   container_name: ambev_developer_evaluation_cache 
  #   image: redis:7.4.1-alpine     
  #   command: redis-server --requirepass ev@luAt10n
  #   environment:
  #      MONGO_INITDB_ROOT_USERNAME: developer
  #      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
  #   ports:
  #      - "6379"